frontend/controllers/AlumniDirectoryController.php
<?php
namespace frontend\controllers;

use frontend\models\DonasiEvent;
use dmstr\bootstrap\Tabs;
use frontend\components\NodeLogger;
use frontend\models\DonasiRutin;
use frontend\models\Mahasiswa;
use frontend\models\MahasiswaSearch;
use frontend\models\MhsMinat;
use frontend\models\MhsPekerjaan;
use frontend\models\MhsSkill;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\helpers\Url;
use yii\web\HttpException;

/**
 * Profile controller
 */
class AlumniDirectoryController extends Controller
{
    public $enableCsrfValidation = false;

    public function actionIndex()
    {
        //$data = Mahasiswa::find();
        $searchModel = new MahasiswaSearch();
        $dataProvider = $searchModel->search($_GET);
        $dataProvider->query->leftJoin('mhs_skill', 'mhs_skill.id_mahasiswa = mahasiswa.id');
        $dataProvider->query->leftJoin('mhs_minat', 'mhs_minat.id_mahasiswa = mahasiswa.id');
        if (isset($_POST['fakultas']))
            $dataProvider->query->andFilterWhere(["fakultas" => $_POST['fakultas']]);
        if (isset($_POST['jurusan']))
            $dataProvider->query->andFilterWhere(["jurusan" => $_POST['jurusan']]);
        if (isset($_POST['thn_masuk']))
            $dataProvider->query->andFilterWhere(["tahun_masuk" => $_POST['thn_masuk']]);
        if (isset($_POST['selected_minat']))
            $dataProvider->query->andFilterWhere(["in", "mhs_skill.skill_id", $_POST['selected_minat']]);
        if (isset($_POST['selected_minat2']))
            $dataProvider->query->andFilterWhere(["in", "mhs_minat.categori_id", $_POST['selected_minat2']]);

        $dataProvider->query->andFilterWhere(['aprroved' => 2])->all();
        $dataProvider->pagination->pageSize = 6;
        if (isset($_POST['fakultas']) != NULL) {
            $f = $_POST['fakultas'];
        } else {
            $f = "";
        }
        if (isset($_POST['jurusan']) != NULL) {
            $j = $_POST['jurusan'];
        } else {
            $j = "";
        }
        if (isset($_POST['thn_masuk']) != NULL) {
            $t = $_POST['thn_masuk'];
        } else {
            $t = "";
        }
        return $this->render('index', [
            'f' => $f,
            'j' => $j,
            't' => $t,
            //  'query' => $data,
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionData()
    {
        $limit = 1;
        $i = $_POST['i'];
        $off = ($i - 1) * $limit;

        $array = Mahasiswa::find()
            ->select("nama_lengkap,lat,lng,foto")
            ->limit($limit)->offset($off)
            ->createCommand()
            ->queryAll();

        return (Json::encode($array));
    }

    public function actionListm($query)
    {
        $ganti = array("'");
        $ganti_baru = array("");
        $baru = str_replace($ganti, $ganti_baru, $query);
        $queryS = "SELECT * FROM master_skill where nama LIKE '" . $baru . "%' ";
        $models = \frontend\models\MasterSkill::findBySql($queryS)->all();
        $items = [];
        foreach ($models as $model) {
            $items[] = [
                'id' => $model->id,
                'name' => $model->nama];
        }
// We know we can use ContentNegotiator filter
// this way is easier to show you here :)
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $items;
    }

    public function actionListmnt($query)
    {
        $ganti = array("'");
        $ganti_baru = array("");
        $baru = str_replace($ganti, $ganti_baru, $query);
        $queryS = "SELECT * FROM master_categori where nama LIKE '" . $baru . "%' ";
        $models = \frontend\models\MasterCategori::findBySql($queryS)->all();
        $items = [];
        foreach ($models as $model) {
            $items[] = [
                'id' => $model->id,
                'name' => $model->nama];
        }
// We know we can use ContentNegotiator filter
// this way is easier to show you here :)
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $items;
    }

    public function actionDetail($id)
    {
        $connection = \Yii::$app->db;
        $ganti = array("'");
        $ganti_baru = array("");
        $baru = str_replace($ganti, $ganti_baru, $id);
        $cek = $baru;
        $donasiJumlah = \frontend\models\Donasi::find()->where(['id_mahasiswa' => $cek]);
        $jumDonasi = $donasiJumlah->sum('jumlah');
        $totDonasi = $donasiJumlah->count('id');
        $donasiRutin = DonasiRutin::find()->where(['id_mahasiswa' => $cek]);
        $jumRutin = $donasiRutin->sum('jumlah');
        $totRutin = $donasiRutin->count('id');
        $donasiEvent = DonasiEvent::find()->where(['donatur' => $cek]);
        $jumEvent = $donasiEvent->sum('jumlah');
        $totEvent = $donasiEvent->count('id');
        $model = $this->findModel($cek);
        $randM = Mahasiswa::find()->orderBy('rand()')->where(['aprroved' => 2])->andWhere(['not in', 'id', [$cek]])->limit(3)->all();
        $totP = ($jumRutin + $jumEvent + $jumDonasi);
        $poin = floor($totP / 100000);
        $modelEx = MhsPekerjaan::find()->where(['mahasiswa_id' => $cek])->all();
        $modelIn = MhsMinat::find()->where(['id_mahasiswa' => $cek])->all();
        $modelSk = MhsSkill::find()->where(['id_mahasiswa' => $cek])->all();
        $trans = $connection->createCommand('(
                        select
                        m.id, m.nama_lengkap, r.id,r.jumlah, CONCAT("Donasi Rutin ", r.bulan, " ", r.tahun) as judul, tanggal
                        from mahasiswa m
                        left join donasi_rutin as r on m.id = r.id_mahasiswa where m.id = ' . $cek . '
                        )
                        union
                        (
                        select
                        m.id, m.nama_lengkap, d.id,d.jumlah, CONCAT("Donasi Onetime ", d.tgl_donasi) as judul, tgl_donasi as tanggal
                        from mahasiswa m
                        left join donasi as d on m.id = d.id_mahasiswa where m.id = ' . $cek . '
                        )
                        union
                        (
                        select
                        m.id, m.nama_lengkap, e.id,e.jumlah, CONCAT("Event : ", ev.judul) as judul, e.tanggal as tanggal_donasi
                        from mahasiswa m
                        left join donasi_event as e on m.id = e.donatur join event as ev on ev.id = e.event where m.id = ' . $cek . '
                        )

                        order by tanggal desc
                        limit 10');
        $tran = $trans->queryAll();
        return $this->render('detail', [
            'model' => $model,
            'jumDonasi' => $jumDonasi,
            'totDonasi' => $totDonasi,
            'jumRutin' => $jumRutin,
            'totRutin' => $totRutin,
            'jumEvent' => $jumEvent,
            'totEvent' => $totEvent,
            'poin' => $poin,
            'randM' => $randM,
            'modelEx' => $modelEx,
            'modelIn' => $modelIn,
            'tran' => $tran,
            'modelSk' => $modelSk
        ]);
    }

    protected function findModel($id)
    {
        if (($model = Mahasiswa::findOne($id)) !== null) {
            return $model;
        } else {
            throw new HttpException(404, 'The requested page does not exist.');
        }
    }
}

frontend/views/alumni-directory/_list_item.php
<?php
// _list_item.php
use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="col-md-6">
    <div class="listing-ver-6">
        <div class="listing-inner">
            <div class="flexslider default-slider">
                <ul class="slides">
                    <li><img src="<?= Yii::$app->request->baseUrl . '/uploads/mhs/' . $model->foto ?>" alt=""></li>
                </ul>
            </div>
            <div class="listing-content" style="padding-bottom: 0">
                <h6 class="title-company"><i class="fa fa-user"></i> <?= $model->nama_lengkap ?></h6>
                  <span class="location">
                    <i class="fa fa-map-marker"></i>
                      <?= $model->kota . ', ' . $model->provinsi ?>
                  </span>
                <ul class="more-info list-inline">
                    <li class="info info-reviews">
                        <ul class="rate list-inline">

                        </ul>
                        <span class="count"></span>
                    </li>
                </ul>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <br/>
                        <br/>
                        <ul class="contact" style="margin: 10px">
                            <li>
                                <i class="fa fa-flag"></i><span><?= $model->namaJurusan->nama_jurusan . ' ' . $model->tahun_masuk ?> </span>
                            </li>
                            <li><i class="fa fa-envelope"></i><span><?= $model->email ?></span>
                            <li><i class="fa fa-home"></i><span><?= $model->alamat ?></span></li>
                            <br>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="listing-content" style="padding: 10px 15px 10px 15px">
                <h6 class="title-tags" style="display: inline-block">Skill : </h6>
                <ul class="tags list-inline" style="display: inline-block">
                    <?php foreach (\frontend\models\MhsSkill::find()->where(['id_mahasiswa' => $model->id])->all() as $sk) { ?>
                        <li><a href="#"><?= $sk->skill->nama ?></a></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <div class="listing-tabs">
            <ul>
                <li><a href="<?= Yii::$app->request->baseUrl.'/alumni-directory/detail?id='.$model->id ?>"><i class="fa fa-file-text-o"></i> View Details</a></li>
            </ul>
        </div>
    </div>
</div>

frontend/views/alumni-directory/detail.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Modal;
use yii\widgets\Pjax;
use yii\helpers\Url;

$this->title = 'Profile ';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="subheader has-bg-image"
         data-bg-image="<?= Yii::$app->request->baseUrl ?>/img/single-business-header.jpg">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="subheader-title"><?= $model->nama_lengkap ?></h3>
                </div>
            </div>
        </div>
    </div>
    <div class="main-content content-restaurant has-bg-image" data-bg-color="f5f5f5">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="listing listing-1">
                        <div class="listing-ver-6">
                            <div class="listing-heading">
                                <h5>Personal Data</h5>
                            </div>
                            <div class="listing-inner">
                                <div class="flexslider default-slider">
                                    <ul class="slides">
                                        <li><img
                                                src="<?= Yii::$app->request->baseUrl . '/uploads/mhs/' . $model->foto ?>"
                                                alt=""></li>
                                    </ul>
                                </div>
                                <div class="listing-content">
                                    <h6 class="title-company"><i class="fa fa-star"></i> <?= $model->pekerjaan ?></h6>
                  <span class="location">
                    <i class="fa fa-bookmark"></i><?= $model->namaJurusan->nama_jurusan ?>
                  </span>
                                    <i class="fa fa-btc"></i><font color="#e74c3c"> <strong>Point Endowment
                                            : <?= \app\components\Angka::toReadableAngka($poin, TRUE) . " Poin"; ?></strong></font>
                                    <ul class="more-info list-inline">
                                        <li class="info info-reviews">
                                            <ul class="rate list-inline">
                                                <li></li>
                                                <li></li>
                                                <li></li>
                                                <li></li>
                                                <li></li>
                                            </ul>
                                            <span class="count"></span>
                                        </li>
                                    </ul>
                                    <br/>
                                    <br/>
                                    <h6 class="title-tags">Skill:</h6>
                                    <ul class="tags list-inline">
                                        <?php foreach ($modelSk as $ModelSkill) { ?>
                                            <li><a><?= $ModelSkill->skill->nama ?>
                                                </a></li>
                                        <?php } ?>
                                        <li>

                                        </li>
                                    </ul>
                                </div>
                                <p class="additional-content">
                                    <?= $model->deskripsi ?>
                            </div>
                        </div>
                    </div>
                    <div class="advertiser-info">
                        <div class="advertiser-header">
                            <h5>Experience</h5>
                        </div>
                        <div class="advertiser-inner">
                            <?php foreach ($modelEx as $experience) { ?>
                                <div class="row">
                                    <div class="col-md-2 col-sm-2">
                                        <ul class="contact">
                                    <span><img src="<?= Yii::$app->request->baseUrl . '/img/karir.png' ?>"
                                               style="width:50px;">
                                                </span>
                                        </ul>
                                    </div>
                                    <div class="col-md-8 col-sm-8">
                                        <ul class="contact">
                                            <span><strong><?= $experience->posisi ?></strong></span><br>
                                            <span><?= $experience->nama_perusahaan ?></span><br>
                                        <span><?= $experience->tanggal_mulai ?>
                                            <?php
                                            if ($experience->status == "") {
                                                echo " s/d sekarang";
                                            } else {
                                                echo " s/d " . $experience->tanggal_akhir;
                                            }
                                            ?>

                                        </span>
                                        </ul>
                                    </div>
                                    <div class="col-md-2 col-sm-2">
                                        <ul class="contact">
                                        </ul>
                                    </div>
                                </div>
                                <hr>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="advertiser-info">
                        <div class="advertiser-header">
                            <h5>Interest</h5>
                        </div>
                        <div class="advertiser-inner">
                            <?php foreach ($modelIn as $interest) { ?>
                                <div class="row">
                                    <div class="col-md-10 col-sm-10">
                                        <ul class="contact">
                                            <span><li><?= $interest->categori->nama ?></li></span>
                                        </ul>
                                    </div>
                                    <div class="col-md-2 col-sm-2">
                                        <ul class="contact">
                                        </ul>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>

                </div>
                <div class="col-md-3">
                    <div class="sidebar-listing">
                        <h5 class="sidebar-listing-title">Similar Person</h5>
                        <?php foreach ($randM as $rand) { ?>
                            <div class="listing-offer">

                                <h6 class="title"><a href="<?= Yii::$app->request->baseUrl.'/alumni-directory/detail?id='.$rand->id ?>"><?= $rand->nama_lengkap ?></a></h6>

                                <div class="listing-offer-thumbnail">
                                    <img src="<?= Yii::$app->request->baseUrl . '/uploads/mhs/' . $rand->foto ?>"
                                         alt="">
                                </div>
                                <div class="listing-offer-content">
                                    <span class="location"><i class="fa fa-map-marker"></i> <?= $rand->kota ?></span>
                            <span class="location"><i class="fa fa-bookmark"></i>
                                <?php if ($rand->jurusan == NULL) {
                                    echo '';
                                } else {
                                    echo $rand->namaJurusan->nama_jurusan;
                                } ?>
                                </span>
                            <span class="location"><i class="fa fa-star"></i> <?php if ($rand->pekerjaan == NULL) {
                                    echo '';
                                } else {
                                    echo $rand->pekerjaan;
                                } ?></span>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .modal-backdrop {
            position: fixed;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            z-index: 0;
            background-color: #000;
        }

    </style>
<?php
if (stristr($_SERVER['HTTP_USER_AGENT'], "Mobile")) { // if mobile browser
    ?>
    <style>
        .modal-content {
            margin-left: 20px;
            margin-right: 20px;
        }
    </style>
    <?php
} else { // desktop browser
    ?>
    <style>
        .modal-content {
            margin-left: 200px;
            margin-right: 200px;
        }
    </style>
    <?php
}
?>

frontend/views/alumni-directory/index.php
<?php
$this->title = 'IKA ITS';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row" style="background-color: #e5e5e5;width: 101%">
    <div class="search-form" style="width: 75%; display: inline-block ">
        <div id="map" style="height: 345px;margin-top: 4px;margin-left: 22px"></div>
    </div>
    <div class="restaurant" style="width: 20%;display: inline-block;">
        <form method="post">
            <div class="content-restaurant" style="padding: 0">
                <div class="sidebar" style="background-color: transparent">
                    <div class="sidebar-fields" style="padding-top: 5px">
                        <div class="custom-select-box">
                            <?php
                            $arr2 = \frontend\models\Fakultas::find()->all();
                            $prd = \yii\helpers\ArrayHelper::map($arr2, 'id', 'nama_fakultas');
                            echo \kartik\widgets\Select2::widget([
                                'name' => 'fakultas',
                                'data' => $prd,
                                'size' => \kartik\widgets\Select2::MEDIUM,
                                'value' => $f,
                                'options' => [
                                    'placeholder' => 'Pilih Fakultas ...',
                                    'id' => 'fakultas',

                                ],
                            ]);
                            ?>
                        </div>

                        <div class="custom-select-box">
                            <?php
                            $arr3 = \frontend\models\Jurusan::find()->all();
                            $prd3 = \yii\helpers\ArrayHelper::map($arr3, 'id', 'nama_jurusan');
                            echo \kartik\widgets\Select2::widget([
                                'name' => 'jurusan',
                                'data' => $prd3,
                                'size' => \kartik\widgets\Select2::MEDIUM,
                                'value' => $j,
                                'options' => [
                                    'placeholder' => 'Pilih Jurusan ...',
                                    'id' => 'jurusan',

                                ],
                            ]);
                            ?>
                        </div>
                        <div class="custom-select-box">
                            <?php
                            $arr4 = [];
                            for ($i = date('Y'); $i >= 1997; $i--)
                                $arr4[] = [
                                    'id' => $i,
                                    'name' => $i
                                ];
                            $prd4 = \yii\helpers\ArrayHelper::map($arr4, 'id', 'name');
                            echo \kartik\widgets\Select2::widget([
                                'name' => 'thn_masuk',
                                'data' => $prd4,
                                'size' => \kartik\widgets\Select2::MEDIUM,
                                'value' => $t,
                                'options' => [
                                    'placeholder' => 'Pilih Tahun Masuk ...',
                                    'id' => 'thn_masuk',

                                ],
                            ]);
                            ?>
                        </div>

                        <div class="custom-select-box">
                            <?=
                            \dosamigos\selectize\SelectizeTextInput::widget([
                                'name' => 'selected_minat',
                                'id' => 'selected_minat',
                                'loadUrl' => ['alumni-directory/listm'],
                                'options' => ['class' => 'form-control','placeholder' => 'Pilih Skill'],
                                'clientOptions' => [
                                    'plugins' => ['remove_button'],
                                    'valueField' => 'id',
                                    'labelField' => 'name',
                                    'searchField' => ['name'],
                                    'create' => false,
                                ]
                            ]);
                            ?>
                        </div>
                        <div class="custom-select-box">
                            <?=
                            \dosamigos\selectize\SelectizeTextInput::widget([
                                'name' => 'selected_minat2',
                                'id' => 'selected_minat2',
                                'loadUrl' => ['alumni-directory/listmnt'],
                                'options' => ['class' => 'form-control','placeholder' => 'Pilih Minat'],
                                'clientOptions' => [
                                    'plugins' => ['remove_button'],
                                    'valueField' => 'id',
                                    'labelField' => 'name',
                                    'searchField' => ['name'],
                                    'create' => false,
                                ]
                            ]);
                            ?>
                        </div>
                    </div>
                    <div class="sidebar-button">
                        <button class="btn btn-primary btn-block"
                                href="<?= Yii::$app->request->baseUrl . '/alumni-directory/fakultas' ?>">Find Now
                        </button>
                    </div>

                </div>
        </form>
    </div>
</div>
<div class="col-md-12">
    <div class="listing listing-1">
        <?=
        \yii\widgets\ListView::widget(['dataProvider' => $dataProvider,
            'layout' => "{items}\n{pager}",
            'options' => [
                'tag' => 'div',
                'class' => 'list-wrapper',
                'id' => 'list-wrapper',
            ],

            'itemView' => function ($model) {
                return $this->render('_list_item', ['model' => $model]);
            },
        ]);
        ?>
    </div>
</div>

</div>
<link rel="stylesheet" type="text/css"
      href="http://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.css"/>
<link rel="stylesheet" type="text/css"
      href="http://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.Default.css"/>

<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js'></script>
<script type='text/javascript' src='http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js'></script>
<script type='text/javascript'
        src='http://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster.js'></script>

<script>
    //    var map = new Map();
    //    //var mapHandler = new MapHandler(map);
    //    var mahasiswa;
    //    $.ajax({
    //        url: '<?//=\yii\helpers\Url::to(['alumni-directory/get-pos'])?>//',
    //        data: {
    //            id: this.value
    //        },
    //        type: 'GET',
    //        success: function (data) {
    //            mahasiswa = JSON.parse(data);
    //            for (var i = 0; i < mahasiswa.length; i++) {
    //                console.log(mahasiswa[i].lat);
    //                var marker = map.drawMarker(mahasiswa[i].lat, mahasiswa[i].lng);
    //                map.addPopup(marker, mahasiswa[i].nama_lengkap, false);
    //            }
    //
    //        }
    //    });


</script>

<script>

    //    var poly = new PolygonEditor({
    //        id: "map",
    //        markerPath: "<?//=Yii::$app->request->baseUrl?>///css_new/js/leaflet/images/",
    //        enableEditor: false
    //    });
    var myURL = "<?= Yii::$app->request->baseUrl.'/img/' ?>";
    var map = L.map('map', {
        center: [10.0, 5.0],
        minZoom: 2,
        zoom: 2
    });
    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYWRtaW5uZXciLCJhIjoiY2o1dHVqbjdlMDA5ZTJxcnh2c3l1cnowOSJ9.t9BkSzPNO0egAXZt5mx--w', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.streets',
        accessToken: 'pk.eyJ1IjoiYWRtaW5uZXciLCJhIjoiY2o1dHVqbjdlMDA5ZTJxcnh2c3l1cnowOSJ9.t9BkSzPNO0egAXZt5mx--w'
    }).addTo(map);
    var myIcon = L.icon({
        iconUrl: myURL + 'images/pin24.png',
        iconRetinaUrl: myURL + 'images/pin48.png',
        iconSize: [29, 24],
        iconAnchor: [9, 21],
        popupAnchor: [0, -14]
    });

    var arrayPolyline = [];
    var fixPolyline = [];

    var a = 1;
    var markerClusters = L.markerClusterGroup();
    function loadMahasiswa() {
        $.ajax({
            data: {
                'i': a,
            },
            url: '<?=\yii\helpers\Url::toRoute(['/alumni-directory/data'])?>',
            type: 'post',
            dataType: "json",
            success: function (data) {
                var marker;
                for (var i = 0, len = data.length; i < len; i++) {
                    if (data[i].lat != null && data[i].lng != null) {
                        //cek di map rumah
                        marker = L.marker([data[i].lat, data[i].lng], {});
                    } else {
                        console.log("mahasiswa cek");
                    }
                    if (marker != null) {
                        var popup =
                            '<center><img width="50px" src=<?= Yii::$app->request->baseUrl."/uploads/mhs/" ?>' + data[i].foto + '></center>' +
                            '<br/><b>Nama :</b> ' + data[i].nama_lengkap;

                        var m = L.marker([data[i].lat, data[i].lng], {icon: myIcon})
                            .bindPopup(popup);

                        markerClusters.addLayer(m);
                        map.addLayer(markerClusters);

                    }
                }
                a++;
//                console.log(data.length);
                if (data.length != 0) {
                    loadMahasiswa();
                    return;

                }else if(data.length==0){
                    console.log("stoop");
                }
                            }

        });
    }

    loadMahasiswa();
</script>